[CUDA_Runtime_jll]
local = "true"
version = "12.9"

[defaults]
parentmodel = "ACCESS-OM2-1"

[models.ACCESS-OM2-01]
dt_seconds = 400
input_prefix = "/path/to/ACCESS-OM2-01/inputs"
outputdir = "/scratch/y99/TMIP/ACCESS-OM2_x_Oceananigans/output/ACCESS-OM2-01"

[models.ACCESS-OM2-025]
dt_seconds = 1800
input_prefix = "/path/to/ACCESS-OM2-025/inputs"
outputdir = "/scratch/y99/TMIP/ACCESS-OM2_x_Oceananigans/output/ACCESS-OM2-025"

[models.ACCESS-OM2-1]
dt_seconds = 5400
input_prefix = "/path/to/ACCESS-OM2-1/inputs"
outputdir = "/scratch/y99/TMIP/ACCESS-OM2_x_Oceananigans/output/ACCESS-OM2-1"
